" content of this file is loaded BEFORE all the plugins
source ~/.vim/plugins.vim  " vundle plugins list
source ~/.vim/global.vim   " general global configuration
source ~/.vim/plugins-config.vim  " configuration for plugins that needs to be set BEFORE plugins are loaded
if has('gui_running')
  source ~/.vim/gvimrc     " gui specific settings
end

source ~/.vim/before.vim   " local BEFORE configs

" after.vim is loaded from ./after/plugin/after.vim
" which should place it AFTER all the other plugins in the loading order
" bindings.vim and local.vim are loaded from after.vim
